---
version: "3.3"
services:
  bookstack:
    container_name: bookstack
    image: solidnerd/bookstack:22.04.02
    depends_on:
    - bookstack_db
    environment:
    - DB_HOST=bookstack_db:3306
    - DB_DATABASE=bookstack
    - DB_USERNAME=bookstack
    - DB_PASSWORD=bookstack
    - APP_URL=http://localhost:8080
    volumes:
    - bookstack-storage:/var/www/bookstack/storage/uploads
    - bookstack-public:/var/www/bookstack/public/uploads
    ports:
    - 8080:8080
    restart: unless-stopped

  bookstack_db:
    container_name: bookstack-db
    image: mysql:8.0.29
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=bookstack
    - MYSQL_USER=bookstack
    - MYSQL_PASSWORD=bookstack
    volumes:
    - bookstack-db:/var/lib/mysql
    - ~/backup:/mnt
    restart: unless-stopped

volumes:
  bookstack-db:
    name: 'bookstack-db'
  bookstack-storage:
    name: 'bookstack-storage'
  bookstack-public:
    name: 'bookstack-public'
